name: Publish binaries
on: [ push ]
  #  push:
  #    tags:
  #      - '*'
  #    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: circom
            asset_name: circom-linux-amd64
          - os: windows-latest
            artifact_name: circom.exe
            asset_name: circom-windows-amd64
          - os: macos-latest
            artifact_name: circom
            asset_name: circom-macos-amd64

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Build
        run: cargo build --verbose --release --locked

      - name: Tar files
        run: tar -cvf circom.tar  -C /home/runner/work/circom/circom/target/release circom

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: target/release/circom.tar
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          asset_name: ${{ matrix.asset_name }}
