name: release circom binaries

on:
  push:
    branches: [ "master", "add_build_release_github_action" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  upload-release:

    runs-on: ubuntu-latest
    needs: [build-linux]

    steps:
    - uses: actions/checkout@v2
    - name: download artifacts
      uses: actions/download-artifact@v3
      with:
        name: uploads    
    - name: upload linux
      id: upload-linux
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://github.com/iden3/circom/tree/master/mkdocs/docs/binaries/
        asset_path: ./circom-linux.zip
        asset_name: circom-linux.zip
        asset_content_type: application/zip

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      id: compile
      run: cargo build --verbose --release
      
    - name: Zip files
      run: zip -r circom-linux /home/runner/work/circom/circom/target/release/circom

    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: uploads
        path: |
          circom-linux.zip
